### PR TITLE
Updated search by name function

### LINKED ISSUE #54: Update searching and filtering functions
Update searching and filtering functions to use array as backend storage

### PR DESCRIPTION
**Pull request by kloudsoft91**
closes #54

### CODE REVIEW

**Comment by kloudsoft91** [comment]
This is ready for review

Note: The final test will continue to fail (and may need rework) till we merge #28 and fix up the json of the already stored data

**Review by joel-yap — CHANGES_REQUESTED** [review]
Think the change might be causing a problem when putting any name into the top searchbox, the filter does not work and there's an error: 
Uncaught TypeError: d.common_names.concat(...).join is not a function
    at index.vue:96:46
    at Proxy.filter (<anonymous>)
    at Proxy.filterByName (index.vue:95:21)
    at Proxy.applyAllFilters (index.vue:53:22)
    at Proxy.handleSearch (index.vue:257:12)
    at callWithErrorHandling (chunk-SBFBVZFQ.js:1779:18)
    at callWithAsyncErrorHandling (chunk-SBFBVZFQ.js:1787:17)
    at emit (chunk-SBFBVZFQ.js:2228:5)
    at Proxy.search (NavigationBar.vue:65:12)
    at _createElementVNode.onInput._cache.<computed>._cache.<computed> (NavigationBar.vue:16:46)

**Comment by kloudsoft91** [comment]
> Think the change might be causing a problem when putting any name into the top searchbox, the filter does not work and there's an error: Uncaught TypeError: d.common_names.concat(...).join is not a function at index.vue:96:46 at Proxy.filter () at Proxy.filterByName (index.vue:95:21) at Proxy.applyAllFilters (index.vue:53:22) at Proxy.handleSearch (index.vue:257:12) at callWithErrorHandling (chunk-SBFBVZFQ.js:1779:18) at callWithAsyncErrorHandling (chunk-SBFBVZFQ.js:1787:17) at emit (chunk-SBFBVZFQ.js:2228:5) at Proxy.search (NavigationBar.vue:65:12) at _createElementVNode.onInput._cache.._cache. (NavigationBar.vue:16:46)

Unfortunately, this is because the json data in the main branch is out of date with the structure the new code expects, we need to fix the data with the correct structure as per my previous commend in #28 and merge those changes before the code in this PR works. Perhaps we should merge that branch in first?

**Review by AdamN2424 — APPROVED** [review]
New search works well, tests passing

**Pull request merged**
